-- MySQL Script generated by MySQL Workbench
-- Fri Mar  4 13:56:42 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizzariadev
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pizzariadev` ;

-- -----------------------------------------------------
-- Schema pizzariadev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzariadev` DEFAULT CHARACTER SET utf8 ;
USE `pizzariadev` ;

-- -----------------------------------------------------
-- Table `pizzariadev`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzariadev`.`Pedidos` (
  `idPedidos` INT NOT NULL AUTO_INCREMENT,
  `detailsp` VARCHAR(500) NOT NULL,
  `subtotal` FLOAT NOT NULL,
  `desconto` FLOAT NOT NULL,
  `total` FLOAT NOT NULL,
  `nome` VARCHAR(500) NOT NULL,
  `email` VARCHAR(500) NOT NULL,
  `telefone` VARCHAR(30) CHARACTER SET 'armscii8' NOT NULL,
  `rua` VARCHAR(500) NOT NULL,
  `numerocasa` INT NOT NULL,
  `complemento` VARCHAR(500) NOT NULL,
  `cep` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idPedidos`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
